# Generated by Django 4.2.7 on 2023-11-29 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='user_address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email_address',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone_number',
            new_name='user_phone_number',
        ),
    ]
