# Generated by Django 4.2.7 on 2023-11-29 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='branch',
            new_name='bank_branch',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='services',
            new_name='bank_services',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='is_islamic',
            new_name='is_islamic_bank',
        ),
    ]
