# Generated by Django 4.2.7 on 2023-11-29 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_rename_branch_bank_bank_branch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='bank_branch',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='is_islamic_bank',
            new_name='is_islamic',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='bank_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='bank_services',
            new_name='services',
        ),
    ]
