# Generated by Django 4.2.7 on 2023-11-30 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0004_bank_account_bank_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='account',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='user',
        ),
    ]
