# Generated by Django 4.2.7 on 2023-11-29 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_amount_account_account_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='account_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='account_type',
            new_name='type',
        ),
    ]
