# Generated by Django 4.2.7 on 2023-11-30 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0005_remove_bank_account_remove_bank_user'),
        ('accounts', '0004_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='banks.bank'),
        ),
    ]
